### PR TITLE
[gradle] Fix task configuration (use configureEach instead all).

### PR DESCRIPTION
**Pull request by terrakok**
Fixes https://github.com/JetBrains/compose-multiplatform/issues/5061

### Fixes - Gradle Plugin
- _(prerelease fix)_ Fix "InvalidUserDataException: Cannot change hierarchy of dependency configuration" on Gradle sync

### CODE REVIEW

**Comment by igordmn** [comment]
Please, add Release Notes (needed for alpha02/beta01). They are not automatically generates from issues, but we should mention them.

**Review by igordmn — APPROVED** [review]

**Comment by igordmn** [comment]
Something like
```
## Releas notes
- _(prerelease fix)_ Fix "InvalidUserDataException: Cannot change hierarchy of dependency configuration" on Gradle sync
```

**Comment by eymar** [comment]
It also fixes: https://github.com/JetBrains/compose-multiplatform/issues/5071

**Comment by terrakok** [comment]
fixes: https://github.com/JetBrains/compose-multiplatform/issues/5038

**Pull request merged**
