### PR TITLE
Sample of common compose with native ui for ios and web

### PR DESCRIPTION
**Pull request by Alex009**
Hi!

I want to add sample with native iOS UIKit UI created by Compose from kotlin.
Also in this sample all app UI located in commonMain, but for iOS we use UIKit composables, for Web use Compose DOM and for android/jvm use Compose UI.

ezgif-3-3924687fe7 ezgif-3-4ee9b0a5b6
ezgif-3-fc12402deb ezgif-3-bbc7ea0c78

### CODE REVIEW

**Comment by Alex009** [comment]
maybe i mark this pull request as draft and wait for some alpha stage of native compose runtime?

**Comment by kareemradwan** [comment]
@Alex009 

Thanks for your contribution, but how I can run this code :)

**Comment by Alex009** [comment]
hi @kareemradwan ! 
clone my fork on branch https://github.com/Alex009/compose-jb/tree/platform-kit-sample
then update submodules - `git submodule update --init --recursive`
then deploy compose to maven local by guide https://github.com/Alex009/compose-jb/tree/platform-kit-sample/compose#multiplatform-build
then open project https://github.com/Alex009/compose-jb/tree/platform-kit-sample/examples/common-platform-uikit and compile by gradle task `build`.

to run ios execute gradle task `./gradlew linkDebugExecutableComposeUIKitArm64`
then open `ios/iosApp.xcodeproj` and run on ios device (now in xcode build phase hardcoded arm64 architecture so you cant run in simulator)

**Comment by kareemradwan** [comment]
@Alex009  I follow the steps but I got an error on   **./scripts/publish** 

the error is : 


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/kradwan/Desktop/android_projects/jetpack_compose/compose-jb/compose/frameworks/support/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':support'.
Unable to find SDK prebuilts at /Users/kradwan/Desktop/android_projects/jetpack_compose/compose-jb/compose/prebuilts/fullsdk-darwin. If you are not using a standard repo-based checkout, please follow the checkout instructions at go/androidx-onboarding.

**Comment by Alex009** [comment]
about compilation of compose we should ask @olonho. @olonho can you help with errors from https://github.com/JetBrains/compose-jb/pull/1734#issuecomment-1022381876 ?

**Comment by kareemradwan** [comment]
@Alex009 

I think I need to download the full android SDK by execute the **./scripts/downloadAndroidSdk .** script.


I am working on it.

**Comment by Tiebe** [comment]
@Alex009 Hey! Awesome contribution here, I'm trying to use `UIViewProtocol` in my own code. I saw that you're using cinterops, but I can't seem to get it to work in my project. (I'm not using native ui btw, I just want to use `UIViewProtocol` from my `iosMain` code.) 

This is my build.gradle.kts:

```
    ios() {
        compilations.getByName("main") {
            cinterop {
                val UIViewProtocol by creating {
                    defFile(project.file("src/iosMain/cinterops/UIViewProtocol.def"))
                }
            }
        }
        
    }
```

but I'm getting the following error:

```
* Where:
Build file '/Users/tiebe/StudioProjects/App/shared/build.gradle.kts' line: 44

* What went wrong:
Script compilation errors:

  Line 44:             cinterop {
                       ^ Unresolved reference: cinterop

  Line 45:                 val UIViewProtocol by creating {
                                                 ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                                                     public fun <T : Any> NamedDomainObjectContainer<TypeVariable(T)>.creating(configuration: TypeVariable(T).() -> Unit): NamedDomainObjectContainerCreatingDelegateProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                                                     public fun <T : Any, U : TypeVariable(T)> PolymorphicDomainObjectContainer<TypeVariable(T)>.creating(type: Class<TypeVariable(U)>, configuration: TypeVariable(U).() -> Unit): PolymorphicDomainObjectContainerCreatingDelegateProvider<TypeVariable(T), TypeVariable(U)> defined in org.gradle.kotlin.dsl
                                                     public fun <T : Any, U : TypeVariable(T)> PolymorphicDomainObjectContainer<TypeVariable(T)>.creating(type: KClass<TypeVariable(U)>): PolymorphicDomainObjectContainerCreatingDelegateProvider<TypeVariable(T), TypeVariable(U)> defined in org.gradle.kotlin.dsl
                                                     public fun <T : Any, U : TypeVariable(T)> PolymorphicDomainObjectContainer<TypeVariable(T)>.creating(type: KClass<TypeVariable(U)>, configuration: TypeVariable(U).() -> Unit): PolymorphicDomainObjectContainerCreatingDelegateProvider<TypeVariable(T), TypeVariable(U)> defined in org.gradle.kotlin.dsl

  Line 46:                     defFile(project.file("src/iosMain/cinterops/UIViewProtocol.def"))
                               ^ Unresolved reference: defFile

3 errors
```

**Pull request closed without merging**
