### PR TITLE
Migrate to notarytool

### LINKED ISSUE #3208: Switch to notarytool
Currently both the [guide](https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Signing_and_notarization_on_macOS/README.md) [gradle plugin](https://github.com/JetBrains/compose-multiplatform/blob/dab4531fe4ffe8509ac4ce7a7336f1016960d67c/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/tasks/AbstractUploadAppForNotarizationTask.kt#L42) use`altool` which has been deprecated in favor of [notarytool](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow#3087734)

### PR DESCRIPTION
**Pull request by DRSchlaubi**
This is currently untested and is mainly to discuss the needed API changes.

I didn't forget about `processUploadToolOutput` and will update it, once I got to try it on a MAC and can take a look at the actual output

Fixes #3208

### CODE REVIEW

**Review by igordmn — COMMENTED** [review]
Thanks!

>  discuss the needed API changes.

We should replace all properties for which we find a replacement, and deprecate others.

Let us know when the PR is ready for review.

**Comment by DRSchlaubi** [comment]
> Thanks!
> 
> > discuss the needed API changes.
> 
> We should replace all properties for which we find a replacement, and deprecate others.
> 
> Let us know when the PR is ready for review.

You can review the API changes, those shouldn't change, it's just that I can't test the response parser yet

**Comment by igordmn** [comment]
The current API change ascProvider -> teamId looks good to me.

And if it is possible to keep `ascProvider` working, we should do that (now it throws an exception).

Is it in the same format as the new parameter teamId?

**Comment by DRSchlaubi** [comment]
> The current API change ascProvider -> teamId looks good to me.
> 
> And if it is possible to keep `ascProvider` working, we should do that (now it throws an exception for existing usages).
> 
> Is it in the same format as the new parameter teamId?

Not at all if I understood the docs correctly, that's why I disabled it

**Comment by igordmn** [comment]
If it is not possible to convert `asc-provider` to `team-id`, then an exception is fine.

**Comment by igordmn** [comment]
The alternative is still use `altool` if `ascProvider` is provided to give people seamless transition for a few month until it stops working in 11.2023

**Comment by DRSchlaubi** [comment]
Is that really worth it? Most people probably don't use that option anyways and this will require adding two seperate implementations of the task to delay a change the have to do anyw

**Comment by igordmn** [comment]
Sounds reasonable, let's just throw an exception

**Comment by DRSchlaubi** [comment]
Ig I need to update the tests as well

**Comment by DRSchlaubi** [comment]
Superseded by #3642

**Pull request closed without merging**
