### PR TITLE
Make desktop preview task fully configuration cache compliant

### PR DESCRIPTION
**Pull request by eygraber**
The issue was in a case where there wasn't a direct dependency on the skiko artifact, the task would attempt to get one at task execution time. This moves that to task configuration time.

### CODE REVIEW

**Comment by eygraber** [comment]
@igordmn any idea on when this could get looked at?

**Comment by igordmn** [comment]
Thanks! Lgtm.

I changed the description to comply our new guidelines that aren't yet enforced. Does it looks okay?

**Comment by eygraber** [comment]
Description looks ok. Do you want to add that an integration test was added, or is that section only for manual QA testing?

**Comment by igordmn** [comment]
> Do you want to add that an integration test was added, or is that section only for manual QA testing?

Thanks, added. This is for all testing.

**Pull request merged**
