### PR TITLE
Update instructions to use JDK-17 or later

### PR DESCRIPTION
**Pull request by dima-avdeev-jb**
It needs to be compatible with the new Kotlin Wizard, which will apply jvmToolchain(17) for all jvm projects.

### CODE REVIEW

**Comment by igordmn** [comment]
These versions in readme are minimal versions. Wizard shouldn't affect them and our support for them.

We can write a recommended version though. Not sure what exactly it should be - "JDK 17", "JDK 19", or "the latest available".

**Comment by dima-avdeev-jb** [comment]
> These versions in readme are the minimal versions. The wizard shouldn't affect them and our support for them.
> 
> We can write a recommended version though. Not sure what exactly it should be - "JDK 17", "JDK 19", or "the latest available".

New wizard projects will work only with JDK 17 out of the box. But, users may change jvmToolchain(11) version in build.gradle.kts file for desktop module.

**Comment by igordmn** [comment]
We should keep JDK 11 in VERSIONING anyway, it doesn't depend on the wizard.

In `Getting started` we can change to JDK 17, it partially depends on wizard.

**Review by igordmn — APPROVED** [review]

**Comment by dima-avdeev-jb** [comment]
Also, we need JDK17 in compose/README (Issue here: https://github.com/JetBrains/compose-jb/issues/2826)

**Comment by frankkienl** [comment]
Does using JDK17 keep compatibility with Android API 33 and lower?

According to these docs, 
https://developer.android.com/build/jdks#compileSdk
API33 uses JDK11, and API34 uses JDK17

**Comment by dima-avdeev-jb** [comment]
@frankkienl 
> Does using JDK17 keep compatibility with Android API 33 and lower?

Yes

**Comment by dima-avdeev-jb** [comment]
This PR is outdated

**Pull request closed without merging**
